/** "EGA remembered fondly": saturated, friendly colours with one shade and one tint each. */
export const P = {
  ink: '#1a2238',          // outlines
  inkSoft: '#2d3a5c',
  frame: '#1b3a5c',        // HUD / letterbox frame
  frameLight: '#2b5a8c',
  panel: '#0f2747',        // HUD panel fill
  panelLine: '#5aa9ff',
  cyan: '#39d6e8',
  cyanDark: '#1aa6b8',
  cyanPale: '#a8f0f6',
  scroll: '#5fdad9',       // riddle scroll paper (cyan like the original)
  scrollEdge: '#2aa6a8',
  white: '#ffffff',
  cream: '#fff6d8',
  yellow: '#ffd23f',
  yellowDark: '#e0a800',
  gold: '#f6c445',
  goldDark: '#c48a12',
  orange: '#ff8c1a',
  red: '#e63946',
  redDark: '#b3202c',
  pink: '#ff6fb1',
  magenta: '#c43bb0',
  purple: '#7b4bb8',
  purpleDark: '#4d2a7f',
  purplePale: '#b79be6',
  blue: '#2f6fe4',
  blueDark: '#1e48a3',
  bluePale: '#8fc1ff',
  skyTop: '#6fbaff',
  skyBottom: '#c9ecff',
  green: '#3fb544',
  greenDark: '#2b8a33',
  greenLight: '#7fe07a',
  grass: '#46b83f',
  grassDark: '#2f8f2c',
  grassLight: '#6fd25e',
  leaf: '#33a537',
  leafLight: '#66d35a',
  brown: '#8b5a2b',
  brownDark: '#5c3a17',
  brownLight: '#c48b4a',
  wood: '#b8763a',
  woodDark: '#7a4a1f',
  rock: '#9aa5b8',
  rockDark: '#6c7a93',
  rockLight: '#c5cddb',
  rockWall: '#7f8ba3',
  rockWallDark: '#5c6883',
  mine: '#7d6a9c',
  mineDark: '#57466f',
  mineLight: '#a690c9',
  snow: '#f4fbff',
  snowShade: '#cfe6f7',
  ice: '#9fd9ff',
  iceDark: '#5fb2e8',
  skin: '#ffd9b3',
  skinDark: '#e0b48c',
  hair: '#7a4a1f',
  elfSkin: '#ffe4c4',
  black: '#000000',
}

export const CAP_COLORS = [P.red, P.green, P.blue]
export const CAP_DARK = [P.redDark, P.greenDark, P.blueDark]
export const NAMED: Record<string, string> = {
  red: P.red, yellow: P.yellow, blue: P.blue, purple: P.purple, green: P.green, white: P.white, brown: P.brown, grey: P.rock, orange: P.orange, pink: P.pink,
}
