// Measures the puzzle content: for every family x grade x tier, samples riddles and reports the
// mean difficulty metric, prompt length, number magnitude and a few examples. Writes
// docs/DIFFICULTY.md. Usage: npx tsx e2e/difficulty.mjs   (or node after building the content bundle)
import { writeFileSync } from 'node:fs'
import { Rng } from '../src/engine/rng.ts'
import { GENERATORS } from '../src/content/generators/index.ts'
import { pickRiddle } from '../src/content/registry.ts'
import { GRADES, TIERS, gradeName } from '../src/content/types.ts'

const N = 300
const gradeLabel = g => g === 0 ? 'K' : String(g)
const lines = []
lines.push('# Difficulty report', '', `Generated by \`e2e/difficulty.mjs\` from ${GENERATORS.length} puzzle families, ${N} samples per family x grade x tier.`, '',
  'The **metric** is each family\'s own difficulty number (bigger is harder; only comparable within a family). ',
  '**words** is the mean number of words in the prompt (reading load). **max number** is the largest number that appears in the prompt or choices (arithmetic load).', '')

function stats(gen, grade, tier) {
  const rng = new Rng(`report-${gen.id}-${grade}-${tier}`)
  let metric = 0, words = 0, maxNum = 0, visuals = 0
  const examples = []
  for (let i = 0; i < N; i++) {
    const r = gen.make(grade, tier, rng)
    metric += r.metric
    words += r.prompt.join(' ').split(/\s+/).length
    const nums = (r.prompt.join(' ') + ' ' + r.choices.map(c => c.text ?? '').join(' ')).match(/\d+(\.\d+)?/g) || []
    for (const n of nums) maxNum = Math.max(maxNum, parseFloat(n))
    if (r.visual || r.choices.some(c => c.visual)) visuals++
    if (examples.length < 2) examples.push(`${r.prompt.join(' / ')} [${r.choices.map((c, k) => (k === r.answer ? '*' : '') + (c.text ?? 'picture')).join(' | ')}]`)
  }
  return { metric: metric / N, words: words / N, maxNum, visuals: visuals / N, examples }
}

lines.push('## Families available per grade', '')
lines.push('| Grade | Reading | Math | Thinking | Total |', '| --- | --- | --- | --- | --- |')
for (const g of GRADES) {
  const gens = GENERATORS.filter(x => x.grades.includes(g))
  const by = a => gens.filter(x => x.area === a).map(x => x.id).join(', ')
  lines.push(`| ${gradeLabel(g)} | ${by('reading')} | ${by('math')} | ${by('thinking')} | ${gens.length} |`)
}
lines.push('')

lines.push('## Ramp per family', '')
for (const gen of GENERATORS) {
  lines.push(`### ${gen.name} (\`${gen.id}\`, ${gen.area})`, '')
  lines.push('| Grade | Tier | metric | words | max number | pictures | example |', '| --- | --- | --- | --- | --- | --- | --- |')
  for (const g of gen.grades) for (const t of TIERS) {
    const s = stats(gen, g, t)
    lines.push(`| ${gradeLabel(g)} | ${t} | ${s.metric.toFixed(1)} | ${s.words.toFixed(1)} | ${s.maxNum} | ${(s.visuals * 100).toFixed(0)}% | ${s.examples[0].replace(/\|/g, '/')} |`)
  }
  lines.push('')
}

lines.push('## Mixed-play sample per grade', '', 'What a child sees over 12 riddles (tiers 1-3 as the levels go up), drawn by the registry with its reading/math/thinking balancing:', '')
for (const g of GRADES) {
  lines.push(`### ${gradeName(g)}`, '')
  const rng = new Rng('mix-' + g); const seen = new Set(); const areas = []
  for (let i = 0; i < 12; i++) {
    const tier = Math.min(3, 1 + Math.floor(i / 4))
    const r = pickRiddle(g, tier, rng, seen, areas); seen.add(r.key); areas.push(GENERATORS.find(x => x.id === r.family).area)
    lines.push(`${i + 1}. *(${r.family}, tier ${tier})* ${r.prompt.join(' ')} — ${r.choices.map((c, k) => (k === r.answer ? '**' : '') + (c.text ?? 'picture') + (k === r.answer ? '**' : '')).join(', ')}`)
  }
  lines.push('')
}
writeFileSync('docs/DIFFICULTY.md', lines.join('\n'))
console.log('wrote docs/DIFFICULTY.md')
